// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhyWd2DN3HHQNSXKiTg2w34uS2jfXoy38',
    appId: '1:759505230331:web:452cb62d6ba5aceedad35e',
    messagingSenderId: '759505230331',
    projectId: 'notesapp-9fb23',
    authDomain: 'notesapp-9fb23.firebaseapp.com',
    storageBucket: 'notesapp-9fb23.firebasestorage.app',
    measurementId: 'G-WQ0PYPWMB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyConNNarbmEhyUueolgnAgF5BGCsbX2Zys',
    appId: '1:759505230331:android:1aaeb7b534a12219dad35e',
    messagingSenderId: '759505230331',
    projectId: 'notesapp-9fb23',
    storageBucket: 'notesapp-9fb23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxh-lZBDGgMCgv4lmaPX4kwe5OODrY0L0',
    appId: '1:759505230331:ios:439d58ac89cd5b14dad35e',
    messagingSenderId: '759505230331',
    projectId: 'notesapp-9fb23',
    storageBucket: 'notesapp-9fb23.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxh-lZBDGgMCgv4lmaPX4kwe5OODrY0L0',
    appId: '1:759505230331:ios:439d58ac89cd5b14dad35e',
    messagingSenderId: '759505230331',
    projectId: 'notesapp-9fb23',
    storageBucket: 'notesapp-9fb23.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhyWd2DN3HHQNSXKiTg2w34uS2jfXoy38',
    appId: '1:759505230331:web:3e65b0aa813d10f6dad35e',
    messagingSenderId: '759505230331',
    projectId: 'notesapp-9fb23',
    authDomain: 'notesapp-9fb23.firebaseapp.com',
    storageBucket: 'notesapp-9fb23.firebasestorage.app',
    measurementId: 'G-5VEC4WT63M',
  );
}
